# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

# Optional: Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: https://docs.gitlab.com/ee/ci/services/index.html
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

# Optional: Install a C compiler, cmake and git into the container.
before_script:
    - sudo apt-get update -yqq
    - sudo apt-get upgrade -yqq
    - sudo apt-get install -yqq --no-install-recommends build-essential
    - sudo apt-get install -yqq --no-install-recommends gcc
    - sudo apt-get install -yqq pkg-config
    - sudo apt-get install -yqq libssl-dev
    - curl https://sh.rustup.rs -sSf | sh -s -- -y

check:cargo:
    script:
    - rustc --version && cargo --version
    - cargo prisma generate
    - cargo check

build:cargo:
  script:
    - rustc --version && cargo --version
    - cargo prisma generate
    - cargo build